### ISSUE TITLE
problem in OS

### ISSUE THREAD

**Issue by walito** [infinidb/infinidb#15]
hi, sorry my english, after compile and run postscrips, I cant start infinidb...

Starting MySQL.                                            [  OK  ]
Shutting down MySQL.                                       [  OK  ]
                                                           [  OK  ]
Starting InfiniDB Database Platform
InfiniDB Database Platform Starting, please wait ......................................................................................................................... FAILED
ERROR: InfiniDB Process failed to start, check log files in /var/log/Calpont

After that, I close my linux session and I try to login but I cant, ssh server is crash...

ssh 10.0.0.13
shell request failed on channel 0

After restart OS, the linux server is out, I cant run 'ls -l' what happend?

**Comment by bhelm** [comment]
The Infinidb Install should not destroy your linux. you could compile it as a non-root user to be sure, and make sure to install it into /usr/local/Calpont rather than any other path.

see here for more informations on the compilation process:
https://github.com/infinidb/infinidb/issues/6

Also note that MariaDB offers precompiled infinidb packages for various platforms that also contain fixes that are currently not available in this repository. If you just want to try infinidb, i would recommend to go with these packages.

**Comment by walito** [comment]
The problem was solved.
I had 4GB ram and maybe there are some problems with the start scripts, when I changed the memory to 16GB this work fine, without any problem.

Maybe this script catch more memory ram, and ssh server is down, and in this moment I can't connect to the server via ssh, but if I run " ./infinidb stop " then I can connect to ssh.

where are those files precompiled? Could you send me the links? please

Thanks in advance

**Comment by bhelm** [comment]
After creating an account on mariadb.com you can go to to the download section and select infinidb there. Here is a link to the section, you need to be logged in: https://mariadb.com/my_portal/download/infinidb
