### ISSUE TITLE
unassignDbrootPmConfig not working

### ISSUE THREAD

**Issue by haimroman** [infinidb/infinidb#20]
InfiniDB version 4.6.5, running on Ubuntu 14.04.3 LTS (an Amazon EC2 virtual machine, if that matters).

I have 1 UM, 1 PM, and 2 DBRoots assigned to that PM.  I'm trying to unassign 1 of the DBRoots from the PM (to compare performance with 2 DBRoots).  But I get the following error:

```
> cmconsole unassignDbrootPmConfig 2 pm1
unassigndbrootpmconfig   Mon Sep  7 14:36:10 2015
DBRoot IDs assigned to 'pm1' = 1, 2
Changes being applied
**** setPmDbrootConfig Failed for 'pm1' : Invalid Parameter passed in getSystemDbrootConfig API
**** Failed Unassign of DBRoots: API Failure return in unassignPmDbrootConfig API
```
And both DBRoots remain assigned to the PM:

```
> cmconsole getModuleConfig
getmoduleconfig   Mon Sep  7 14:38:08 2015
Module Name Configuration
Module 'pm1' Configuration information

ModuleType = pm
ModuleDesc = Performance Module #1
ModuleIPAdd NIC ID 1 = 127.0.0.1
ModuleHostName NIC ID 1 = localhost
DBRootIDs assigned  = 1, 2
```

I have the InfiniDB Admin Guide for version 4.6.  It does *not* mention the unassignDbrootPmConfig command!  I haven't found any reference to this on the net, either.  Any ideas?  Thanks

**Comment by davidhilldallas** [comment]
There is a help command in the cmconsole that will tell you the parameters.

cmconsole

> help unassignDbrootPmConfig

On Mon, Sep 7, 2015 at 9:40 AM, haimroman <notifications@github.com> wrote:

> InfiniDB version 4.6.5, running on Ubuntu 14.04.3 LTS (an Amazon EC2
> virtual machine, if that matters).
>
> I have 1 UM, 1 PM, and 2 DBRoots assigned to that PM. I'm trying to
> unassign 1 of the DBRoots from the PM (to compare performance with 2
> DBRoots). But I get the following error:
>
> > cmconsole unassignDbrootPmConfig 2 pm1
> unassigndbrootpmconfig   Mon Sep  7 14:36:10 2015
> DBRoot IDs assigned to 'pm1' = 1, 2
> Changes being applied
> **** setPmDbrootConfig Failed for 'pm1' : Invalid Parameter passed in getSystemDbrootConfig API
> **** Failed Unassign of DBRoots: API Failure return in unassignPmDbrootConfig API
>
> And both DBRoots remain assigned to the PM:
>
> > cmconsole getModuleConfig
> getmoduleconfig   Mon Sep  7 14:38:08 2015
> Module Name Configuration
> Module 'pm1' Configuration information
>
> ModuleType = pm
> ModuleDesc = Performance Module #1
> ModuleIPAdd NIC ID 1 = 127.0.0.1
> ModuleHostName NIC ID 1 = localhost
> DBRootIDs assigned  = 1, 2
>
> I have the InfiniDB Admin Guide for version 4.6. It does *not* mention
> the unassignDbrootPmConfig command! I haven't found any reference to this
> on the net, either. Any ideas? Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/infinidb/infinidb/issues/20>.
>



-- 
------------------
David Hill
InfiniDB Development/Customer Support
MariaDB Corporation
http://www.mariadb.com

**Comment by haimroman** [comment]
used it:
```
> cmconsole help unassignDbrootPmConfig
help   Tue Sep  8 14:54:30 2015

   Command:     unassignDbrootPmConfig

   Description: Unassign DBroots from a Performance Module
                This command could be used before a DBRoot is removed

   Arguments:   Required: List of Dbroot IDs to be unassigned
                Required: Performance Module Name
```
And that's what I specified.  Maybe the DBRoot should be specified as something other than "2".  But what?  Every help & info command I saw just specifies the roots as 1, 2, etc.

**Comment by haimroman** [comment]
Sorry, new to this forum.  Closed this topic by mistake (re-opened it)

**Comment by davidhilldallas** [comment]
Hum, not sure what is going on.. I just tried the same thing on my system
with the same version and it worked..
Check and post the error logs, mayb they will point to what the issue is.

here is what I did:

[root@srvss2 ~]# cc

Calpont InfiniDB Command Console
   enter 'help' for list of commands
   enter 'exit' to exit the Calpont InfiniDB Command Console
   use up/down arrows to recall commands


Active Alarm Counts: Critical = 0, Major = 0, Minor = 0, Warning = 0, Info
= 0

Critical Active Alarms:

InfiniDB> getst
getstorageconfig   Tue Sep  8 10:20:14 2015

System Storage Configuration

Performance Module (DBRoot) Storage Type = internal
System Assigned DBRoot Count = 1
DBRoot IDs assigned to 'pm1' = 1


InfiniDB> getcal
getcalpontsoftwareinfo   Tue Sep  8 10:20:19 2015

Name        : infinidb-platform            Relocations: (not relocatable)
Version     : 4.6.5                             Vendor: MariaDB, Inc.
Release     : 1                             Build Date: Sat 02 May 2015
03:45:32 PM CDT
Install Date: Tue 08 Sep 2015 10:17:55 AM CDT      Build Host:
srvbuilder.mariadb.com
Group       : Applications                  Source RPM:
infinidb-4.6.5-1.src.rpm
Size        : 24809469                         License: Copyright (c) 2014
InfiniDB, Inc., all rights reserved; redistributable under the terms of the
GPL, see the file COPYING for details.
Signature   : (none)
Packager    : support@mariadb.com
URL         : http://www.mariadb.com/
Summary     : InfiniDB software binaries
Description :
InfiniDB binary files
Build Flags: -g0 -O3 -fno-strict-aliasing -fno-tree-vectorize -flto

InfiniDB> adddbroot 1
adddbroot   Tue Sep  8 10:20:26 2015

 New DBRoot IDs added = 2

InfiniDB> stopsystem
stopsystem   Tue Sep  8 10:20:35 2015

This command stops the processing of applications on all Modules within the
Calpont System

   Checking for active transactions
           Do you want to proceed: (y or n) [n]: y

   System being stopped now...
   Successful stop of System

InfiniDB> assign 1 pm1
assigndbrootpmconfig   Tue Sep  8 10:20:57 2015


**** assignPmDbrootConfig Failed : DBRoot ID 1 already assigned to 'pm1'

**** getStorageConfig Failed :  Invalid Parameter passed in
assignPmDbrootConfig API

**** assignPmDbrootConfig Failed : dbroot 1 doesn't exist

**** Failed Assign of DBRoots: Invalid Parameter passed in
assignPmDbrootConfig API
InfiniDB> assign 2 pm1
assigndbrootpmconfig   Tue Sep  8 10:21:01 2015

DBRoot IDs assigned to 'pm1' = 1

Changes being applied

DBRoot IDs assigned to 'pm1' = 1, 2

   Successfully Assigned DBRoots

InfiniDB> starts
startsystem   Tue Sep  8 10:21:04 2015
   System being started, please wait...
   Successful start of System

InfiniDB> unassign 2 pm1
unassigndbrootpmconfig   Tue Sep  8 10:21:50 2015

**** unassignDbrootPmConfig Failed, pm1 has to be in a MAN_OFFLINE state
InfiniDB> stops
stopsystem   Tue Sep  8 10:21:56 2015

This command stops the processing of applications on all Modules within the
Calpont System

   Checking for active transactions
           Do you want to proceed: (y or n) [n]: y

   System being stopped now...
   Successful stop of System

InfiniDB> unassign 2 pm1
unassigndbrootpmconfig   Tue Sep  8 10:22:10 2015

DBRoot IDs assigned to 'pm1' = 1, 2

Changes being applied

DBRoot IDs assigned to 'pm1' = 1

   Successfully Unassigned DBRoots

InfiniDB>


On Tue, Sep 8, 2015 at 9:57 AM, haimroman <notifications@github.com> wrote:

> Sorry, new to this forum. Closed this topic by mistake (re-opened it)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/infinidb/infinidb/issues/20#issuecomment-138592310>.
>



-- 
------------------
David Hill
InfiniDB Development/Customer Support
MariaDB Corporation
http://www.mariadb.com

**Comment by haimroman** [comment]
Now it's working!

```
InfiniDB> unassign 2 pm1
unassigndbrootpmconfig   Sun Sep 13 06:36:10 2015

DBRoot IDs assigned to 'pm1' = 1, 2

Changes being applied

DBRoot IDs assigned to 'pm1' = 1

   Successfully Unassigned DBRoots 

InfiniDB> getstorageconfig
getstorageconfig   Sun Sep 13 06:36:50 2015

System Storage Configuration

Performance Module (DBRoot) Storage Type = internal
System Assigned DBRoot Count = 1
DBRoot IDs assigned to 'pm1' = 1

DBRoot IDs unassigned = 2
```

My guess is that I didn't stop the system before trying to unassign, though my error message didn't indicate it (unlike yours).  

We're running the same versionm though my output of getcalpontsoftwareinfois much shorter:

```
InfiniDB> getcal
getcalpontsoftwareinfo   Sun Sep 13 06:33:23 2015

SoftwareVersion = 4.6.5
SoftwareRelease = 1
```

I installed infinidb from Debian packages.  I see you installed from an RPM.

Thanks for your help!

**Comment by haimroman** [comment]
I'm pretty much done.  

I think part of the problem was that I was working on amazon machines, where the IP might change on every boot.  David, thanks for your help.
