### ISSUE TITLE
idbmysql memory leakage

### ISSUE THREAD

**Issue by danyrlz** [infinidb/infinidb#22]
Hello,

We're using infinidb on a server with 64G RAM . It is doing relatively high amount of data inserts (about 50M rows/day and 5-8G data daily).

The problem we experience is mysqld memory leakage. The process gradually occupies the RAM. As soon as it's exausted the server starts to swap. When the swap reaches 80% the infinidb restarts the system and all the memory is released. Then it starts over.
Mysqld process restart also releases the occupied memory.

We've tried several mysql optimisations with no result.

Any suggestions for further troubleshooting?

Thank you in advance.

**Comment by brianrp** [comment]
What version of InfiniDB are you using?
How much swap is on each system?
1 UM?

Its been my experience with MySQL that this is what it does, slowly consume all the memory it can.

Are you using cpimport instead of the MySQL INSERT command?
It doesn't go thru the MySQL front end.

Bp - another InfiniDB user.

**Comment by danyrlz** [comment]
Hello,

Issue is confirmed on Infinidb 4.6 Beta, 4.6.6 and 4.6.7-1, mysql 5.1.73-log.
Current swap is 32G

We're using MySQL INSERT.
