### ISSUE TITLE
can there be multiple PMs (performance modules) on the same computer?

### ISSUE THREAD

**Issue by haimroman** [infinidb/infinidb#23]
I'm asking because I just tried to add a 3rd PM, and put it on the same machine as the 1st, and it failed.  I'm purposely not giving many details on this thread, because I really want an answer to the posted question --- can there be more than one PM on the same machine?

Thanks

**Comment by rdempseyidb** [comment]
Not in any manner that is supported by the configuration tools.

It is theoretically possible by hand editing the config and using different ports, etc. but it's not practical.

**Comment by haimroman** [comment]
Thanks, rdempseyidb.  Now I'm trying to add more computers to my infinidb system.  The addModule command doesn't do that, and I haven't found any way other than running postConfigure from Scratch (I hope I don't have to reinstall infinidb from scratch).  Am I missing something?

**Comment by bhelm** [comment]
what is the reason for adding more than one pm per machine? like rdempseyidb said, it should be possible by manually editing the config files, but i would not recommend that because it will take some time to get it set up correctly (and infinidb is sometimes cryptic when it wants to tell you, what is wrong).

if i really want to start multiple pm's on one machine, i would use some kind of virtual machine or chroot (with ip alias). that should be the fastes and error-free way, as all infinidb cluster management machanisms can work as usual.

**Comment by haimroman** [comment]
Thanks, everyone.  We're now doing one PM per machine.
