### ISSUE TITLE
adding additional machines to existing infinidb

### ISSUE THREAD

**Issue by haimroman** [infinidb/infinidb#24]
I have an infinidb with 2 machines.  One machine has the UM & PM1, the other has PM2.  I want to add another 2 machines (each with one PM), and move some of the existing DBroots to the new PMs.

I tried addModule:

```
> cc addModule pm 1 172.30.1.179

addmodule   Sun Oct 25 13:32:07 2015

Adding Modules pm3, please wait...

**** addModule Failed: API Failure return in addModule API
```

getModuleConfig shows pm3, but of course there is no InfiniDB software on this new machine.  

What should I be doing on this new machine?  Just install the infinidb packages (Ubuntu 14.04)?  Some other command/script?  Do I have to install the entire thing from scratch?  Thx

**Comment by bhelm** [comment]
make sure you have added the ssh key to the new machine so that the machine you are executing the addmodule command can login to the new machine without password. try to ssh to the new machine to make sure that it goes through without questions. using ssh keys is recommended, alternatively you can try `cc addModule pm 1 172.30.1.179 rootpw` if you can not use ssh keys.

do a `tail -F /var/log/Calpont/*.log` while executing this command to see whats going wrong.

if you still have problems, install the infinidb packages manually on the target system. i have noticed that installing the debian packages does not pull all dependencies, i always have to `aptitude install expect` manually.

**Comment by sexygeoff** [comment]
I'm having the same problem, haimroman, did you ever figure it out?

**Comment by davidhilldallas** [comment]
Make sure your infinidb packages exist in the HOME directory, /root or /home/infinidb of non root install

**Comment by gcleaves** [comment]
What if I'm using the binary tar file? Will that work if I just place the tar file in /root?  Or must I use the rpms?

**Comment by davidhilldallas** [comment]
In the current servers was installed with the binary package, then it will look for the binary tar package

**Comment by gcleaves** [comment]
It still doesn't work for me. I've placed and expanded every tar, to be safe, into /root on the remote machine but continue to receive the same error message. I get the same error when I purposely use the wrong SSH password, so somehow I think the problem is on the local, main server.

    InfiniDB> addModule pm 1 192.168.10.178 2rf223f32
    addmodule   Tue Jan 12 22:20:12 2016

    Adding Modules pm2, please wait...

    **** addModule Failed: File Open error from addModule API
I saw mention of a tool called binary_installer.sh in another issue. Is that what does the actually install?

I've tried enabling debug logging in the calpontConsole but don't see any /var/log/Calpont/debug.log file at all.

I'm using version 4.6.7-1, any further ideas would be greatly appreciated.

**Comment by davidhilldallas** [comment]
OK, can you check and possible post what gets logged in the debug and error
log at the time the addmodule is done.
Those located in /var/log/Calpont. Also do you see a file in the /tmp
related to installer.log?

The binary_installer.sh is the script that should get called, if its
getting that fair. That would be shown in the debug logs and its should be
located in /usr/local/Calpont/bin

David

On Tue, Jan 12, 2016 at 3:28 PM, Geoffrey Cleaves <notifications@github.com>
wrote:

> It still doesn't work for me. I've placed and expanded every tar, to be
> safe, into /root on the remote machine but continue to receive the same
> error message. I get the same error when I purposely use the wrong SSH
> password, so somehow I think the problem is on the local, main server.
>
> InfiniDB> addModule pm 1 192.168.10.178 2rf223f32
> addmodule   Tue Jan 12 22:20:12 2016
>
> Adding Modules pm2, please wait...
>
> **** addModule Failed: File Open error from addModule API
>
> I saw mention of a tool called binary_installer.sh in another issue. Is
> that what does the actually install?
>
> I've tried enabling debug logging in the calpontConsole but don't see any
> /var/log/Calpont/debug.log file at all.
>
> I'm using version 4.6.7-1, any further ideas would be greatly appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/infinidb/infinidb/issues/24#issuecomment-171062404>.
>



-- 
------------------
David Hill
InfiniDB Development/Customer Support
MariaDB Corporation
http://www.mariadb.com

**Comment by gcleaves** [comment]
The are no log files, even though I think I have debug logging enabled:

    InfiniDB> getLogConfig
    getlogconfig   Tue Jan 12 22:43:14 2016

    Calpont System Log Configuration Data

    System Logging Configuration File being used: /etc/rsyslog.d/49-calpont.conf

    Module    Configured Log Levels
    ------    ---------------------------------------
    pm1       Critical Error Warning Info Debug Data

Logs:

````
[root@infinidb Calpont]# pwd
/var/log/Calpont
[root@infinidb Calpont]# ls -lha
total 48K
drwxr-xr-x. 6 root root 4.0K Dec 30 16:25 .
drwxr-xr-x. 8 root root 4.0K Jan 10 03:33 ..
drwxr-xr-x. 2 root root 4.0K Dec 30 15:43 archive
drwxr-xr-x. 2 root root 4.0K Dec 30 15:43 corefiles
drwxr-xr-x. 3 root root 4.0K Dec 30 15:43 data
-rw-r--r--. 1 root root   78 Jan 11 18:55 load_brm.log1
-rw-r--r--. 1 root root  191 Jan 11 18:55 reset_locks.log1
-rw-r--r--. 1 root root   61 Jan 11 18:55 save_brm.log1
drwxr-xr-t. 2 root root 4.0K Dec 30 15:57 trace
-rw-r--r--. 1 root root 9.3K Jan 12 22:38 uiCommands.log
````
Nothing related to installer.log is in /tmp :(

```/etc/rsyslog.d/49-calpont.conf``` looks like this, are those ```-``` symbols in front of the filenames supposed to be there? Could the duplicate entries be causing problems?

```
# Calpont Database Platform Logging
local1.crit -/var/log/Calpont/crit.log
local1.err -/var/log/Calpont/err.log
local1.warning -/var/log/Calpont/warning.log
local1.info -/var/log/Calpont/info.log
local1.debug -/var/log/Calpont/debug.log
local2.crit -/var/log/Calpont/data/data_mods.log

local1.=crit -/var/log/Calpont/crit.log
local1.=err -/var/log/Calpont/err.log
local1.=warning -/var/log/Calpont/warning.log
local1.=info -/var/log/Calpont/info.log
local1.=debug -/var/log/Calpont/debug.log
local2.=crit -/var/log/Calpont/data/data_mods.log
local2.=crit -/var/log/Calpont/data/data_mods.log
```

Thanks for your help so far, keep the ideas coming, they are much appreciated.

**Comment by davidhilldallas** [comment]
shot, hard to debug without the logs.. as you show, they seem to be setup.
You could try restarting rsyslog and run the addmodule and see if the logs
show up.

On Tue, Jan 12, 2016 at 3:51 PM, Geoffrey Cleaves <notifications@github.com>
wrote:

> The are no log files, even though I think I have debug logging enabled:
>
> InfiniDB> getLogConfig
> getlogconfig   Tue Jan 12 22:43:14 2016
>
> Calpont System Log Configuration Data
>
> System Logging Configuration File being used: /etc/rsyslog.d/49-calpont.conf
>
> Module    Configured Log Levels
> ------    ---------------------------------------
> pm1       Critical Error Warning Info Debug Data
>
> Logs:
>
> [root@infinidb Calpont]# pwd
> /var/log/Calpont
> [root@infinidb Calpont]# ls -lha
> total 48K
> drwxr-xr-x. 6 root root 4.0K Dec 30 16:25 .
> drwxr-xr-x. 8 root root 4.0K Jan 10 03:33 ..
> drwxr-xr-x. 2 root root 4.0K Dec 30 15:43 archive
> drwxr-xr-x. 2 root root 4.0K Dec 30 15:43 corefiles
> drwxr-xr-x. 3 root root 4.0K Dec 30 15:43 data
> -rw-r--r--. 1 root root   78 Jan 11 18:55 load_brm.log1
> -rw-r--r--. 1 root root  191 Jan 11 18:55 reset_locks.log1
> -rw-r--r--. 1 root root   61 Jan 11 18:55 save_brm.log1
> drwxr-xr-t. 2 root root 4.0K Dec 30 15:57 trace
> -rw-r--r--. 1 root root 9.3K Jan 12 22:38 uiCommands.log
>
> Nothing related to installer.log is in /tmp :(
>
> /etc/rsyslog.d/49-calpont.conf looks like this, are those - symbols in
> front of the filenames supposed to be there? Could the duplicate entries be
> causing problems?
>
> # Calpont Database Platform Logging
> local1.crit -/var/log/Calpont/crit.log
> local1.err -/var/log/Calpont/err.log
> local1.warning -/var/log/Calpont/warning.loglocal1.info -/var/log/Calpont/info.log
> local1.debug -/var/log/Calpont/debug.log
> local2.crit -/var/log/Calpont/data/data_mods.log
>
> local1.=crit -/var/log/Calpont/crit.log
> local1.=err -/var/log/Calpont/err.log
> local1.=warning -/var/log/Calpont/warning.log
> local1.=info -/var/log/Calpont/info.log
> local1.=debug -/var/log/Calpont/debug.log
> local2.=crit -/var/log/Calpont/data/data_mods.log
> local2.=crit -/var/log/Calpont/data/data_mods.log
>
> Thanks for your help so far, keep the ideas coming, they are much
> appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/infinidb/infinidb/issues/24#issuecomment-171069644>.
>



-- 
------------------
David Hill
InfiniDB Development/Customer Support
MariaDB Corporation
http://www.mariadb.com

**Comment by gcleaves** [comment]
Now we're getting somewhere! I removed those ```-``` from the conf.d rsyslog file, restarted rsyslog per your suggestion, and now have logs.

````
[root@infinidb Calpont]# cat debug.log 
Jan 12 23:00:29 infinidb ProcessManager[11913]: 29.343643 |0|0|0| I 17 CAL0000: MSG RECEIVED: Add Module request
Jan 12 23:00:29 infinidb ProcessManager[11913]: 29.405995 |0|0|0| E 17 CAL0000: line: 4454 addModule - ERROR: Package not found: /root/infinidb-platform-4.6.7-1*.rpm
Jan 12 23:00:29 infinidb ProcessManager[11913]: 29.406130 |0|0|0| I 17 CAL0000: ADDMODULE: ACK received from Process-Monitor, return status = 3
Jan 12 23:00:29 infinidb ProcessManager[11913]: 29.406240 |0|0|0| I 17 CAL0000: ADDMODULE: ACK back to sender
Jan 12 23:00:53 infinidb ProcessManager[11913]: 53.404316 |0|0|0| I 17 CAL0000: MSG RECEIVED: Add Module request
Jan 12 23:00:53 infinidb ProcessManager[11913]: 53.466269 |0|0|0| E 17 CAL0000: line: 4454 addModule - ERROR: Package not found: /root/infinidb-platform-4.6.7-1*.rpm
Jan 12 23:00:53 infinidb ProcessManager[11913]: 53.466318 |0|0|0| I 17 CAL0000: ADDMODULE: ACK received from Process-Monitor, return status = 3
Jan 12 23:00:53 infinidb ProcessManager[11913]: 53.466375 |0|0|0| I 17 CAL0000: ADDMODULE: ACK back to sender
````
I think maybe I misunderstood on which host the packages need to exist in /root. I put them on the remote server. I'll now put them on the local host and try again. Don't like that it's looking for RPMs though, since I used the binary package for install.

**Comment by davidhilldallas** [comment]
ok, they need to be on the local server and then they will be pushed down
to the remote serve rand installed. but its looking for the rpm packages,
instead of the binary packages, like you said. there is an entry in the
Calpont.xml that should say how it was installed, variable is
EEpackageType. If that says 'rpm', you can change to 'binary' if you want
to install 'binary' packages.




On Tue, Jan 12, 2016 at 4:04 PM, Geoffrey Cleaves <notifications@github.com>
wrote:

> Now we're getting somewhere! I removed those - from the conf.d rsyslog
> file, restarted rsyslog per your suggestion, and now have logs.
>
> [root@infinidb Calpont]# cat debug.log
> Jan 12 23:00:29 infinidb ProcessManager[11913]: 29.343643 |0|0|0| I 17 CAL0000: MSG RECEIVED: Add Module request
> Jan 12 23:00:29 infinidb ProcessManager[11913]: 29.405995 |0|0|0| E 17 CAL0000: line: 4454 addModule - ERROR: Package not found: /root/infinidb-platform-4.6.7-1*.rpm
> Jan 12 23:00:29 infinidb ProcessManager[11913]: 29.406130 |0|0|0| I 17 CAL0000: ADDMODULE: ACK received from Process-Monitor, return status = 3
> Jan 12 23:00:29 infinidb ProcessManager[11913]: 29.406240 |0|0|0| I 17 CAL0000: ADDMODULE: ACK back to sender
> Jan 12 23:00:53 infinidb ProcessManager[11913]: 53.404316 |0|0|0| I 17 CAL0000: MSG RECEIVED: Add Module request
> Jan 12 23:00:53 infinidb ProcessManager[11913]: 53.466269 |0|0|0| E 17 CAL0000: line: 4454 addModule - ERROR: Package not found: /root/infinidb-platform-4.6.7-1*.rpm
> Jan 12 23:00:53 infinidb ProcessManager[11913]: 53.466318 |0|0|0| I 17 CAL0000: ADDMODULE: ACK received from Process-Monitor, return status = 3
> Jan 12 23:00:53 infinidb ProcessManager[11913]: 53.466375 |0|0|0| I 17 CAL0000: ADDMODULE: ACK back to sender
>
> I think maybe I misunderstood on which host the packages need to exist in
> /root. I put them on the remote server. I'll now put them on the local host
> and try again. Don't like that it's looking for RPMs though, since I used
> the binary package for install.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/infinidb/infinidb/issues/24#issuecomment-171074902>.
>



-- 
------------------
David Hill
InfiniDB Development/Customer Support
MariaDB Corporation
http://www.mariadb.com

**Comment by gcleaves** [comment]
Well it seems to have worked with the RPM package! Tomorrow (it's 11pm here in Spain) I'll try adding the DBroot and enabling the new pm module. 

While I've got you, David, can you answer something I'm not clear on? I've read in the docs that I can improve user concurrency by adding UM modules. However, I can't add UM modules because I installed with the 'multi' option. Now I've been able to add the new PM module, does that include another UM module with it? Will I ever be able to improve user concurrency?

Second question: Am I committing career suicide by basing my company's BI service on InfiniDB, now that it is EOL? Will MariaDB continue to put out bug fixes or new features? Tough question!

**Comment by davidhilldallas** [comment]
While I've got you, David, can you answer something I'm not clear on? I've
read in the docs that I can improve user concurrency by adding UM modules.
However, I can't add UM modules because I installed with the 'multi'
option. Now I've been able to add the new PM module, does that include
another UM module with it? Will I ever be able to improve user concurrency?

First, what is your system now? did it have 1 um and 1 pm OR was it a
combined system with just 1 pm and you have now added a second pm? If it's
the second situation, it will also have  User Module functionality on it
and you can run the mysql console there. If its the first, 1 um and 2 pms
now. Then you would need to add a second um.

Second question: Am I committing career suicide by basing my company's BI
service on InfiniDB, now that it is EOL? Will MariaDB continue to put out
bug fixes or new features? Tough question!

That is known at this time what our road map is with InfiniDB. The current
InfiniDB is fairly stable, so you hopefully will not run into any new bugs.
features will be different.


Good luck, David

On Tue, Jan 12, 2016 at 4:21 PM, Geoffrey Cleaves <notifications@github.com>
wrote:

> Well it seems to have worked with the RPM package! Tomorrow (it's 11pm
> here in Spain) I'll try adding the DBroot and enabling the new pm module.
>
> While I've got you, David, can you answer something I'm not clear on? I've
> read in the docs that I can improve user concurrency by adding UM modules.
> However, I can't add UM modules because I installed with the 'multi'
> option. Now I've been able to add the new PM module, does that include
> another UM module with it? Will I ever be able to improve user concurrency?
>
> Second question: Am I committing career suicide by basing my company's BI
> service on InfiniDB, now that it is EOL? Will MariaDB continue to put out
> bug fixes or new features? Tough question!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/infinidb/infinidb/issues/24#issuecomment-171078623>.
>



-- 
------------------
David Hill
InfiniDB Development/Customer Support
MariaDB Corporation
http://www.mariadb.com
