### ISSUE TITLE
Select while deleting causes table to lock

### ISSUE THREAD

**Issue by gcleaves** [infinidb/infinidb#27]
Lock in the sense that no queries return results, just run forever.

Sometimes I need to reload a day's worth of data because of an error in the original load. I first delete the day's data, which typically takes 40 minutes. But often when I perform a select statement on the table that is being deleted from, the select never responds and neither does the delete. I need to restart the system. I just gave up on my typical delete after 3 hours. My problem doesn't alway occur. When I restart the system, begin my delete and then test a select statement, the select statement works.

Does anybody have any advice on what could be happening?

Using version 4.6.7.

**Comment by bhelm** [comment]
Try to avoid deleting millions of rows by your design. Maybe you can avoid the big delete by using the calDropPartitions function to delete a large amount of rows at once. This is not like a fine tuned delete, but is very quick and actually frees disk space. Alternatively, insert in different tables and drop/truncate whole tables if possible.
As workaround, if your system freezed, try a “killall DMLProc“ instead of a complete restart. 

It's possible you are facing a deadlock I have sometimes. In this case, it may help to have as few dbroots as possible (1 per server max).

**Comment by gcleaves** [comment]
Thanks for this informative response. I could possibly load each day into its own separate table and use a view to union all the tables for select purposes. Do you know if InfiniDB would have any performance problems with the view which unions all the tables?

**Comment by bhelm** [comment]
i have re-read your initial question; yes, its a bit tricky to purge a full day of bad data from an infinidb table and reload it. if you have some kind of primary key, you can try to update the old data. (load the new data to a seperate table and use UPDATE table JOIN .. Syntax to fix the fields that were wrong.)

another way would be to load the current table into a temporary one (INSER INTO newtable SELECT FROM oldtable WHERE daten < bad-day) and insert the fixed version there. after all is done use the RENAME TABLE command to rename the tables so that newtable takes place of the old one. RENAME TABLE can rename multiple tables at once in an atomic transaction.

i have never used views with infini; but using views with union would possible work for simple search queries, but as soon as you start using group by or joins over multiple days, i can imagine that this part wont be processed by infini but by mysql instead (mysql will delegate the query to the InfiniDB storageengine for each table seperately and merge the results at the end). it *may* work if you always group by day or your result sets are small enought to be post-processed by mysql, but im just guessing. if you go this route, let me know the results.
