### ISSUE TITLE
Infinidb - redistributeDB

### ISSUE THREAD

**Issue by XtreamData** [infinidb/infinidb#38]
Good day all,

I can't find too much info on this utility within InfiniDB. 
As I understand when running redistributeDB this will 'balance' data across dbroots on a PM?
- Is  that correct?
- Can we be loading more data on that PM while this process is running?
- Should this process be run on all PM's individually or can I run it on the OAM PM only and it will do it on all PM's?
- What will cause it to fail?
- What does it actually do (tech speak will help)?

We are experiencing the dbroots to be unbalanced and need a way to make them all equal again wrt to free space. 

We are also considering adding more dbroots to the PM's. Any advise?

Thanks,
Frik

**Comment by brianrp** [comment]
I have always ran it from pm1.
It needs to be executed when no writes are happening, no cpimports, inserts or updates. They can cause it to fail. You can disable writes with a cmconsole command. Disable/enableDbWrites?

It will balance data across all the pm's. But due to several factors, it can't perfectly rebalance data. Small tables may not require space on every pm. Some allocated segments may not be completely full. Etc.

It maintains the maps that tell the system where to find the data. As data is moved the maps are updated.

I believe it reads the maps when it starts up and if writes are happening while it runs, when it gets to places in the map that changed, from other activity, that will cause it to fail.

So far, for me, restarting the system, or it restarting itself when the system detected the maps were broken, has repaired the maps and everything recovered. But I don't advise having to do, or cause that to happen.

At least that is my experience with it.



Sent from my iPhone

On Jun 15, 2016, at 3:12 AM, XtreamData <notifications@github.com<mailto:notifications@github.com>> wrote:


Good day all,

I can't find too much info on this utility within InfiniDB.
As I understand when running redistributeDB this will 'balance' data across dbroots on a PM?

  *   Is that correct?
  *   Can we be loading more data on that PM while this process is running?
  *   Should this process be run on all PM's individually or can I run it on the OAM PM only and it will do it on all PM's?
  *   What will cause it to fail?
  *   What does it actually do (tech speak will help)?

We are experiencing the dbroots to be unbalanced and need a way to make them all equal again wrt to free space.

We are also considering adding more dbroots to the PM's. Any advise?

Thanks,
Frik

-

**Comment by brianrp** [comment]
suspendDatabaseWrites
resumeDatabaseWrites

**Comment by XtreamData** [comment]
Thank you Brian for the precise info. We'll apply and give feedback.

**Comment by bhelm** [comment]
I have tried it once (let it run for some hours on one pm) and it did nothing noticeable. let us know how it works for you.

If you are updating (not inserting) data on infinidb, the database size can easily grow 5x or 10x of its original "straight imported" size. one solution would be to do a INSERT INTO .. SELECT into a new table and rename it afterwards to the original name. This will also "redistribute" the data to be even on all pms. Depending on data size, this process can take minutes to hours to complete. you will need to stop updates to the database for that time or some way to incrementally sync the changes that have accumulated since start of the procedure (easy if you have a last_modified timestamp).

One thing that i have not tried but could work if you are not using cpimport to load data is this tool: https://www.percona.com/doc/percona-toolkit/2.1/pt-online-schema-change.html
if you start it with ENGINE=InfiniDB it will create a new table with the same schema, create triggers on the old table to sync changes to the new one and copies the whole table over. that way, you dont need to stop writes to the table. for performance reasons you will want to choose a larger --chunk-time, something like 10 or 20 seconds or even more will do.

**Comment by brianrp** [comment]
I recalled some usage items.
To start it, it runs in the background
redistributeDB start
To get status/progress info
redistributeDB status
To stop it
redistributeDB stop
When complete, or if you stop it and allow writes, you should clear it so it starts fresh the next time you use it.
redistributeDB clear

**Comment by bhelm** [comment]
Did you get any results with redistributeDB?
