### ISSUE TITLE
Is there some limited for MariaDB ColumnStore, such as max length for varchar data type is 8000? 

### ISSUE THREAD

**Issue by chenxinglong** [infinidb/infinidb#44]
If I want to store TEXT field, and compute it, What can i do?

**Comment by brianrp** [comment]
TEXT is not a valid data type for InfinDB. I change the table definition for those fields to VARCHAR(n).
Use whatever length you want, I use 100.

When you cpimport the data it will truncate the column in the data to the length of the column in the table.

Note that this can be problematic if the column has multibyte characters (utf8) and one of those characters gets split (only the first 1 or 2 bytes recorded) because it straddles the end of the column.

bp
