### ISSUE TITLE
Moving table with Billion to new database 

### ISSUE THREAD

**Issue by a3plusb3** [infinidb/infinidb#48]
Hello 
I have an infinidb system with a couple thousand tables, and billions per table. 
I would like to perform some open heart surgery by moving the tables in a single database to different databases by altering the catalog. 
This is for security purposes...
Has this been done before? is it possible? 
Any advise would be welcome. 
Thanks

**Comment by bhelm** [comment]
i have not done such a thing yet. im just wondering what your security considerations are, because mysql ACLs work similar on database and table level. Or are you talking about moving the tables to different infinidb systems?

an alternative could be to use the mariadb maxscale database proxy, which has even more security features than mysql ACLs.

**Comment by a3plusb3** [comment]
Hi Thanks for the info. 
I have used cpimport with a pipe as in the 4.6.7 documentation 
fyi here is the command to move data across. 

idbmysql -e 'select * from source_table;' -N SRCDB| /usr/ local/Calpont/bin/cpimport -j501 -s '\t' –fSTDIN
