### ISSUE TITLE
infinidb storage concepts + cpimport 

### ISSUE THREAD

**Issue by a3plusb3** [infinidb/infinidb#49]
Hello Fellow infinidb users. 

I have been trying to find information on how cpimport work with infinidb storage. 
as per the documentation any changes to the data creates a version buffer. 
is this true for cpimport. 
Does anyone have a system diagram/workflow diagram of how cpimport works?

**Comment by bhelm** [comment]
No diagrams here. Afaik, cpimport bypasses the mysql backend and works directly on the infinidb storage (write) engine. infinidb is not strong on its documentation, so you best chance of reliable informations is to look at the source code of cpimport and the functions used.

i have never seen incomplete cpimports, even if cpimport crashed midair. also, all inserted rows appear at once when cpimport is finished. so cpimport maintains the data integrity.
there seems to be no size limit on how much data cpimport can load (no version buffer oferflowed error). also, cpimport locks the table exclusively, so that no other cpimports or DML queries can be run on this table.

so yes, especially by the fact that the "version buffer" never overflows with cpimport, it looks like it does not use the version buffer, while still making the cpimport atomic.

https://github.com/infinidb/infinidb/blob/master/writeengine/bulk/cpimport.cpp

**Comment by dhall-InfiniDB** [comment]
cpimport bypasses the version buffer. All data is appended to the files as a stream. When complete the table is locked while the high water mark is moved and the extentmap updated.

**Comment by a3plusb3** [comment]
thanks. for the info.
