### ISSUE TITLE
is there a way to rebuild the extent map in infinidb .  

### ISSUE THREAD

**Issue by a3plusb3** [infinidb/infinidb#52]
we shutdown and restarted the system and on of the primary mount point was not available
on restart 
are shutdown was done the data mount point remount and system started up again. 
however now we cannot see the extent map in calpontsys.systables; 
 
is there a way to rebuild the extent map? 

we get this error when querying calpontsys.tables; 

Invalid Range from HWM for lbid 8704, range size should be <= blocksReadAhead: HWM 0, dbroot 1, highfbo 1023, lowfbo 512, blocksReadAhead 512, range size -511#012#012

**Comment by bhelm** [comment]
i have problems to understand what your problem is. please check your spelling.

doing a restart/initialization of the system does not damage anything. but if the storage configuration is messed up, its possible that infinidb cannot load all informations needet.

please attach the complete /var/log/Calpont/debug.log beginning from the start procedure so we can better see whats going on. also give the output of calpontConsole getSystemInfo, calpontConsole getStorageConfig and calpontConsole getStorageStatus.

**Comment by a3plusb3** [comment]
More info... 
we hae 4 PM's
The mount point on pm1 during the initial install existed~/Calpont/data1/
we then created a mount point on data1 
on startup of from pm1 the mount point did not get mounted this then resulted in the cluster seeing the original ~/Calpont/data1 which had an incorrect extent map which replicated to all the sites. 
hence we need to recover the extent map.

**Comment by a3plusb3** [comment]
[debug.zip](https://github.com/infinidb/infinidb/files/760463/debug.zip)

**Comment by rdempseyidb** [comment]
There is no way to rebuild the extent map because it contains one-way mappings to logical block numbers. You'll have to revert to a backup (you are backing up, right?).

**Comment by a3plusb3** [comment]
Hi Yes we have a backup of the brm saves. 
Thanks
